name: wakemeup
version: '1.1.4'
summary: WakeMeUp is a tiny Wake-On-Lan utility to wake up a wol device in standby
description: |
   Wake-On-Lan is a computer networking standard that allows a computer to be 
   turned on or awakened by a network message.  The computer must be configured
   to enable Wake-On-Lan and be in a state where the network card is montiored.
   This is usually in the standby or sleep state.

grade: stable
confinement: strict
base: core18

title: WakeMeUp
website: https://github.com/frossm/wakemeup
contact: wakemeup@fross.org
issues: https://github.com/frossm/wakemeup/issues
icon: graphics/PostIt512.png
license: MIT

# Enable LZO compression for faster startup
compression: lzo

apps:
  wakemeup:
    command: bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/wakemeup.jar

parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2021.10.24'
    maven-options: [install]

  wakemeup:
    plugin: maven
    source: https://github.com/frossm/wakemeup.git
    source-branch: master
    source-type: git
    after: [library]
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs

plugs:
   rpncalc-network:
      interface: network